//
// Created by hanil on 4/26/2023.
//

#ifndef SFML_PROJECTS_IMAGES_H
#define SFML_PROJECTS_IMAGES_H

enum images
{
    PALKIA, CHARIZARD, BLAZIKEN, PIKACHU,
    SCEPTILE, SQUIRTLE, POKEBALL, ASH, TRAINER,
    PALKIA_FRONT, CHARIZARD_FRONT, BLAZIKEN_FRONT,
    PIKACHU_FRONT, SCEPTILE_FRONT, SQUIRTLE_FRONT, JESSE, BATTLE,PHASER, TITLE, START,

    LAST_TEXTURE
};

#endif //SFML_PROJECTS_IMAGES_H
